spring.application.name=Place
server.port=8080

# MongoDB Atlas
spring.data.mongodb.uri=${DB_URI}
spring.data.mongodb.database=Placementor
spring.data.mongodb.auto-index-creation=true

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000



# Logging
logging.level.org.springframework=INFO
logging.level.com.example.PlaceMentor=DEBUG